/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#9fa0a0",
        "surface-dim": "#dcd9d9",
        "inverse-on-surface": "#f3f0ef",
        "on-secondary-fixed-variant": "#474646",
        "on-secondary": "#ffffff",
        "inverse-surface": "#313030",
        "secondary-container": "#e5e2e1",
        "secondary-fixed": "#e5e2e1",
        "tertiary-fixed-dim": "#c6c6c7",
        "surface-tint": "#994700",
        "secondary-fixed-dim": "#c8c6c5",
        "error": "#ba1a1a",
        "on-surface-variant": "#584235",
        "secondary": "#5f5e5e",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#753400",
        "primary-fixed-dim": "#ffb68b",
        "surface-variant": "#e5e2e1",
        "surface-container-highest": "#e5e2e1",
        "outline-variant": "#e0c0af",
        "on-primary-container": "#5c2800",
        "primary-fixed": "#ffdbc8",
        "tertiary": "#5d5f5f",
        "on-background": "#1c1b1b",
        "surface-container": "#f0edec",
        "on-tertiary-fixed": "#1a1c1c",
        "primary": "#994700",
        "on-tertiary-fixed-variant": "#454747",
        "primary-container": "#ff7a00",
        "surface": "#fcf9f8",
        "tertiary-fixed": "#e2e2e2",
        "surface-bright": "#fcf9f8",
        "on-primary-fixed": "#321200",
        "on-secondary-fixed": "#1c1b1b",
        "surface-container-high": "#ebe7e7",
        "on-tertiary": "#ffffff",
        "background": "#fcf9f8",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "inverse-primary": "#ffb68b",
        "surface-container-low": "#f6f3f2",
        "on-tertiary-container": "#353737",
        "on-surface": "#1c1b1b",
        "on-error-container": "#93000a",
        "outline": "#8c7263",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#656464"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Manrope"],
        "label": ["Manrope"]
      },
      borderRadius: {"DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px"},
    },
  },
}